# -*- coding: utf-8 -*-
"""02_cyclone_severities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmwjhnbAE_u4qGfbvINQ1EtpOCso-Dra
"""

!pip install beautifulsoup4

from bs4 import BeautifulSoup
import csv

with open('Cyclone_data.html', 'r', encoding='utf-8') as file:
  html_data = file.read()

from bs4 import BeautifulSoup
import csv


soup = BeautifulSoup(html_data, 'html.parser')

tables = soup.find_all('table')

csv_filename = "cyclone_data.csv"
with open(csv_filename, 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)

    headers = ['Month', 'Sl.No.', 'Year', 'Max Intensity', 'Initial Date', 'Lat(°N)', 'Lon(°E)']
    csvwriter.writerow(headers)

    for table in tables:
        month_header = table.find_previous_sibling('tr')
        if month_header and 'Month of' in month_header.text:
            month = month_header.text.strip().replace('Month of ', '')
        else:
            month = "Unknown"

        rows = table.find_all('tr')

        for row in rows[1:]:
            cells = row.find_all('td')
            if cells:
                sl_no = ""
                year = ""
                max_intensity = ""
                initial_date = ""
                lat = ""
                lon = ""

                if len(cells) >= 1:
                    sl_no = cells[0].text.strip()
                if len(cells) >= 2:
                    year = cells[1].text.strip()
                if len(cells) >= 3:
                    max_intensity = cells[2].text.strip()
                if len(cells) >= 4:
                    initial_date = cells[3].text.strip()
                lat = cells[4].text.strip()
                lon = cells[5].text.strip()

                row_data = [
                    month,
                    sl_no,
                    year,
                    max_intensity,
                    initial_date,
                    lat,
                    lon
                ]
                csvwriter.writerow(row_data)

print(f"CSV file '{csv_filename}' created successfully with all data combined.")